logging.file: build/eureka.log

server.port: ${PORT:8761}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

management.security.enabled: false
endpoints.health.sensitive: false
