spring.application.name: reporting

logging:
  level.org.springframework.cloud: DEBUG
  level.org.springframework.cloud.sleuth: TRACE
  level.org.springframework.cloud.sleuth.log: DEBUG
  level.org.springframework.cloud.sleuth.trace: DEBUG
  level.org.springframework.cloud.sleuth.instrument.rxjava: DEBUG
  level.com.wavefront.spring: DEBUG

server.port: ${PORT:9995}

spring.rabbitmq.host: ${RABBIT_HOST:localhost}

logging.file: build/reporting.log

spring.cloud.stream:
  binder.rabbit.default.maxConcurrency: 5


endpoints.health.sensitive: false
endpoints.default.web.enabled: true
management.security.enabled: false
management.endpoints.web.base-path: /

spring.zipkin.sender.type: web
spring:
  sleuth:
    reactor:
      enabled: false
    baggage:
      correlation-fields:
        - TEST-COMMUNICATION-TYPE
      remote-fields:
        - TEST-COMMUNICATION-TYPE

spring.cloud.function.definition: events
spring.cloud.stream.bindings.events-in-0.destination: events

spring.cloud.config.label: main